//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2015-12-08 15:15:22 AuthBy:cmm
//     对此文件的更改可能会导致不正确的行为，并且如果													   ·
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace DataEntity
{	
    [Table("UserInfo")]
	public partial class UserInfoEntity
    {
		#region 属性
		[Key]		
		/// <summary>
		/// key
		/// </summary>		
		public int Id { get; set; }
				
		/// <summary>
		/// 
		/// </summary>		
		public string UserName { get; set; }
				
		/// <summary>
		/// 
		/// </summary>		
		public int Age { get; set; }
				
		/// <summary>
		/// 
		/// </summary>		
		public string JobNo { get; set; }
				
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreatedTime { get; set; }
		 
      #endregion

	  		///<summary>
		///set default value
		///</summary>
		public void SetDefaultValue()
		{
						if (this.UserName == null) this.UserName = "";
			if (this.JobNo == null) this.JobNo = "";
			if (this.CreatedTime.Year<1900) this.CreatedTime =  new DateTime(1900,01,01);

		}


		#region 字段
		public static class Fields
		{
	   		public const string Id = "Id";
	   
	   		public const string UserName = "UserName";
	   
	   		public const string Age = "Age";
	   
	   		public const string JobNo = "JobNo";
	   
	   		public const string CreatedTime = "CreatedTime";
	   
	   	  }
		#endregion

		#region	基本SQL
        public static class Sql 
        {
		  
			//查询sql
			public static string selectSql="SELECT Id,UserName,Age,JobNo,CreatedTime FROM TCInterVacationOVDResource.dbo.UserInfo a WITH(NOLOCK) ";
        }
		#endregion


    }
}

